# Read KRF files
Kick off 2025-10-31

## Initial settings

In [ ]:
from pathlib import Path
import pandas as pd
import geopandas as gpd
import shapely

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.3f}'.format)

## Read KRF files from source

In [4]:
dir_krf = '/Users/hkang/damask/gis/assets/KRF-v3'

path_node = Path(dir_krf, 'KRF_ver3_NODE.shp')
path_line = Path(dir_krf, 'KRF_ver3_LINE.shp')
path_poly = Path(dir_krf, 'KRF_ver3_CATCHMENt.shp')

In [ ]:
gdf_node = gpd.read_file(path_node)
gdf_node.head(3)

,OBJECTID,NODE_ID,NODE_DID,NODE_X,NODE_Y,WGM_ID,WGM_NM,WTM_ID,WTM_NM,WAM_ID,WAM_NM,DAM_NM,BO_NM,LU_RCH_ID,LU_RCH_DID,RU_RCH_ID,RU_RCH_DID,LD_RCH_ID,LD_RCH_DID,RD_RCH_ID,RD_RCH_DID,NODE_SN,NODE_DIV,RCH_NUM,S_FLAG,E_FLAG,C_FLAG,DAM_FLAG,BO_FLAG,WGM_FLAG,WTM_FLAG,WAM_FLAG,SB_FLAG,R_FLAG,FLAG_ID,geometry
0,1,60020106,6002010600,126.379,33.484,None,None,None,None,None,None,None,None,60020103,6002010300,None,None,None,None,None,None,06,00,1.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0000001,POINT (126.37909 33.4842)
1,2,60020104,6002010400,126.397,33.484,None,None,None,None,None,None,None,None,60020102,6002010200,None,None,None,None,None,None,04,00,1.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0000001,POINT (126.39736 33.48412)
2,3,60020102,6002010200,126.403,33.486,None,None,None,None,None,None,None,None,60020101,6002010100,None,None,None,None,None,None,02,00,1.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0000001,POINT (126.40295 33.48579)

In [ ]:
gdf_line = gpd.read_file(path_line)
gdf_line.head(3)

,OBJECTID,RCH_ID,RCH_DID,BRU_X,BRU_Y,BLL_X,BLL_Y,Shape_Leng,INODE_ID,INODE_DID,ONODE_ID,ONODE_DID,U_DIR,LU_RCH_ID,LU_RCH_DID,RU_RCH_ID,RU_RCH_DID,DI_DIR,DI_RCH_ID,DI_RCH_DID,D_DIR,LD_RCH_ID,LD_RCH_DID,RD_RCH_ID,RD_RCH_DID,CAT_ID,CAT_DID,RIV_ID,RIV_NM,RCH_SN,RCH_DIV,GEO_TRIB,RCH_LEN,TOTAL_LEN,CUM_LEN,O_FLAG,E_FLAG,S_FLAG,DC_RIV_NM,DC_RIV_ID,CUM_AREA,geometry
0,1,10150311,1015031100,127.354,37.805,127.287,37.782,0.080,10150311,1015031100,10150312,1015031200,N,None,None,None,None,L,10150310,1015031000,L,10150312,1015031200,None,None,10150311,1015031100,1024020,0,11,00,4.000,7.508,7.508,7.508,0.000,0.000,1.000,상동천,1024000,24.135,"LINESTRING (127.28666 37.78253, 127.28684 37.7..."
1,2,10150813,1015081300,127.373,37.605,127.342,37.594,0.038,10150813,1015081300,10150814,1015081400,L,10150811,1015081100,10150812,1015081200,R,10150810,1015081000,L,10150814,1015081400,None,None,10150812,1015081200,1024210,0,13,00,2.000,3.576,12.650,12.650,0.000,0.000,0.000,문호천,1002710,49.835,"LINESTRING (127.37293 37.60277, 127.37276 37.6..."
2,3,10150707,1015070700,127.408,37.649,127.373,37.636,0.061,10150707,1015070700,10150801,1015080100,R,10150706,1015070600,10150705,1015070500,None,None,None,L,10150801,1015080100,None,None,10150707,1015070700,1024130,0,07,00,2.000,5.733,29.221,28.997,0.000,0.000,0.000,사기막천,1002710,78.068,"LINESTRING (127.40824 37.6385, 127.40818 37.63..."

In [ ]:
gdf_poly = gpd.read_file(path_poly)
gdf_poly.head(3)

,OBJECTID,CAT_ID,CAT_DID,BRU_X,BRU_Y,BLL_X,BLL_Y,Shape_Leng,Shape_Area,streamname,BASIN_ID,BASIN_NM,MB_ID,MB_NM,SB_ID,SB_NM,CAT_SN,CAT_DIV,AREA,PERI,CAT_FLAG,geometry
0,1,41010109,4101010900,126.738,34.613,126.667,34.526,0.321,0.003,None,41,섬진강남해,4101,섬진강서남해,410101,강진천,09,00,26.740,32.818,0.000,"POLYGON ((126.73839 34.55878, 126.73834 34.558..."
1,2,41010110,4101011000,126.729,34.541,126.680,34.506,0.144,0.001,None,41,섬진강남해,4101,섬진강서남해,410101,강진천,10,00,10.430,14.391,0.000,"POLYGON ((126.72929 34.52608, 126.72921 34.526..."
2,3,41010111,4101011100,126.766,34.559,126.706,34.494,0.235,0.002,None,41,섬진강남해,4101,섬진강서남해,410101,강진천,11,00,20.403,23.912,0.000,"POLYGON ((126.75863 34.52628, 126.75872 34.525..."

In [8]:
path_checkpoint = Path('checkpoint')
if not path_checkpoint.exists():
    path_checkpoint.mkdir()
    print(f'{path_checkpoint.resolve()} created')
else:
    print(f'{path_checkpoint.resolve()} already exists')

/Users/hkang/dev/pj-stations/checkpoint already exists

In [9]:
gdf_node.to_file(Path(path_checkpoint, 'krf_node.gpkg'), driver='GPKG')
gdf_line.to_file(Path(path_checkpoint, 'krf_line.gpkg'), driver='GPKG')
# split file fitted for github repo 
idh = len(gdf_poly) // 2
gdf_poly.iloc[:idh].to_file(Path(path_checkpoint, 'krf_catchment_1.gpkg'), driver='GPKG')
gdf_poly.iloc[idh:].to_file(Path(path_checkpoint, 'krf_catchment_2.gpkg'), driver='GPKG')

## Plot KRF on a map

In [ ]:
# set True when it is continued from here
continue_from_here = False
if continue_from_here:
    gdf_node = gpd.read_file(Path(path_checkpoint, 'krf_node.gpkg'))
    gdf_line = gpd.read_file(Path(path_checkpoint, 'krf_line.gpkg'))

    gdf_poly1 = gpd.read_file(Path(path_checkpoint, 'krf_catchment_1.gpkg'))
    gdf_poly2 = gpd.read_file(Path(path_checkpoint, 'krf_catchment_2.gpkg'))
    gdf_poly = pd.concat([gdf_poly1, gdf_poly2])

    print("node, line, poly files are successfully loaded")

node, line, poly files are successfully loaded